services:
  - type: web
    name: geg-flight-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENSKY_USER
        sync: false
      - key: OPENSKY_PASS
        sync: false
